# Generated by Django 3.2 on 2021-04-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0002_studentnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.CharField(default='', max_length=30)),
                ('time', models.IntegerField(default='', max_length=30)),
            ],
        ),
    ]
